language: c
sudo: false
os:
    - linux
branches:
  except:
    - /^lean-.*$/
env:
  global:
  - secure: "HxnRtl6pMc+nbszQgDgvMuroMG5AuviULPb0MxPfEIZqYSwKALgc0ILXc89kJyf9rFfpsUdKGmtrGOytzXIp8Yuxvp+fnk/rtuuRyMLeWA0sJ75/Jn+l0BKVid6LNwl7bA4aMOSkjL85kaxU2e5HtlROUkiAgmdAcV10BoK7Vh7yC/S4Zl3kzyCQd8AGSxk0AbeQrb9vK7T1+gWVkEjUFtUsFJ3q5SGrO/j3825qLoRnYj/bKUgtYExQNKjTnTYMbeok+mKJEO1VbLeTk1ri8bLyO2x25lhGImaJSgdPOzuH905ALrf+EHkKm/FYvy5w+zERiuidwwFK5OqVOVWsD5W0G5rYKmDKpzSd39FNnrvb2Tzl2kCin70j6SDOXyZ+4k/iGJpBnOtx3+Ez4gsBDWLIba1c5EXvzhvPoycddgSLBY2LNz4EJI+YqbBTBxG7dVr4NmKKjPowFerVMLM10SgkH9ZZjbAVMxejUJTzp/4gxTanlWm/xds5uC0E0mraLY1H1yzGtwij/lVJN8RGbuhvW9jluLYQzfN7Hb/MReBXTKwdVo5SnsZzv9GEM56IsQXgIhzRoHAuDHd8rS1rfXGaOVfsbYK7pBjtx9j+Pq3BNSPlIL5u4j2JXH6QVJSNaK1npCq81S21dIBfYTP49ft28bhgVE0czkD7kl3fCCk="
  - secure: "lf8RIS4LVTJD2aHRw4+HMsD71pZDDQRy3u3XvIv5u7wAm01hI4xGyQuCoWu8kTFzawK3VeRyLdxbE6BDqwCqOabn1l+uc3/DPzNCRjF2JSm+OPd0Yy+DcpE10V0R36zFb7rJKeiBYn6XvmwIpwuX4HEfwY4LjP2xxxKBofkpAMD/4wiml6UFR7bf8cGXWI2NXfNeHkT9g0j6nE+bwF81BAjgk2Hs4rZYnZkGGhKztcVRmYmvKiNXGFc+vQDuv0XUiC443h2od3Zd6ZCujC6wAD7IiIr7hNRYLesvObGjQgn9DLwGGHAsOmMCpGDfCmtoL8N7HZPcYgA0QGxKmpyveQ1K9NEMGdX2zl2zs1/GrD7v1jPHsyRW1nEFW5o2gdCjI1uYIoXXZdbGqOEsmFJjy3NvAeG00qP/EfrwObUMhZYmWnnVUClN8RChTH3asQdJ1bIkS8pLN3QIIrKxUWmgEPWnOLY5s7Gcs4l8GetlQckMIqX+pLnTzm38lAXTYwexpZnbhpD1oYTpOev7Lm6uAWDxBIp37+6Zcuwzdm1qrJI7rq/0W4FUY9LmUMRvhz19bcxpqST/Rux+bYVyIxaxG9C/faMoPPN8z5PKvh5qHKmon0hk3OrsnFJ4W2Bd/0iqUIEQXQKcGTYPnAagQX0h6hGDd9uc92v1r125GCuD6VU="

cache:
  directories:
    - $TRAVIS_BUILD_DIR/test/
    - $TRAVIS_BUILD_DIR/src/
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - mkdir $HOME/scripts || echo ""
  - export PATH="$HOME/scripts:$PATH"
  - cp travis_long.sh $HOME/scripts/travis_long
  - chmod +x $HOME/scripts/travis_long
  - (git status | grep  -e "Changes not staged for commit:"); RESULT=$?
  - if [ $RESULT -eq 0 ]; then git checkout -f HEAD ; fi
  - git clean -d -f -q
  - ./purge_olean.sh
  - rm mathlib.txt || true
  - export LEAN_VERSION=lean-`lean --run scripts/lean_version.lean`

jobs:
  include:
    - env: TASK="check Lean proofs"
      stage: Pre-build-1
      script:
        - travis_long "timeout 2400 leanpkg test" | python scripts/detect_errors.py

    - env: TASK="check Lean proofs"
      stage: Pre-build-2
      script:
        - travis_long "timeout 2400 leanpkg test" | python scripts/detect_errors.py

    - env: TASK="check Lean proofs"
      stage: Test
      script:
        - travis_long "leanpkg test"
        - lean --recursive --export=mathlib.txt src/
        - travis_long "leanchecker mathlib.txt"
        - sh scripts/deploy_nightly.sh

    - env: TASK="check install scripts"
      language: python
      python:
        - "3.6"
      install:
        - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
        - echo $SOMEVAR
      os:
        - linux
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - sh scripts/remote-install-update-mathlib.sh --global
        - source $HOME/.profile
        - update-mathlib

    - env: TASK="check install scripts"
      language: sh
      install:
        - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
      os:
        - osx
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - sh scripts/remote-install-update-mathlib.sh
        - source $HOME/.profile
        - update-mathlib

    - env: TASK="check dev scripts"
      sudo: true
      language: python
      python:
        - "3.6"
      install:
        - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
      os:
        - linux
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - cd scripts
        - echo y | bash setup-dev-scripts.sh --global
        - source $HOME/.profile
        - update-mathlib
        - cache-olean
        - cache-olean --fetch

    - env: TASK="check dev scripts"
      language: sh
      install:
        - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
      os:
        - osx
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - cd scripts
        - echo y | bash setup-dev-scripts.sh
        - source $HOME/.profile
        - update-mathlib
        - cache-olean
        - cache-olean --fetch

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
