name: cancel CI for obsolete pushes

on: [push]

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: semorrison/workflow-run-cleanup-action@v0.2.2
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
